name: CI

on: [push]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite-actions/setup-pnpm
      - run: pnpm check
      - run: pnpm build
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite-actions/setup-pnpm
      - run: pnpm test
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox: [true, false]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite-actions/setup-pnpm
      - if: matrix.sandbox == true
        run: echo 'SANDBOX=true' >> $GITHUB_ENV
      - run: pnpm --filter vite-plugin-qiankun-lite build
      - run: pnpm e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
