name: CI

on: [push]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite-actions/setup-pnpm
      - run: pnpm check
      - run: pnpm build
