name: Snapshot

on: workflow_dispatch

jobs:
  release:
    name: Publish snapshot version
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite-actions/setup-pnpm
      - name: Publish snapshot
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm prepare-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
